name: Bug Report
description: Report a bug or issue with the GitHub Issue Management System
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `./claude/setup.sh`
        2. Start Issue Manager with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected by this bug?
      options:
        - Issue Manager
        - Worker (worker1, worker2, worker3)
        - Git Worktree System
        - Communication (agent-send.sh)
        - Setup/Installation
        - GitHub Integration
        - tmux Environment
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      value: |
        - OS: (e.g., macOS 14.0, Ubuntu 22.04)
        - Shell: (e.g., zsh, bash)
        - tmux version: (run `tmux -V`)
        - Claude CLI version: (run `claude --version`)
        - gh CLI version: (run `gh --version`)
        - Git version: (run `git --version`)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (from logs/send_log.txt or terminal output)
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots, configuration files, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues to avoid duplicates
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I have tested this with the latest version of the system
          required: true